// Lista de invitados para la página privada de la raíz. Al agregar un
// invitado, crea su carpeta en app/(invitados)/<enlace>/ y agrégalo aquí.
export const GRUPOS_INVITADOS: { grupo: string; invitados: { nombre: string; enlace: string }[] }[] = [
  {
    grupo: "Lista 1",
    invitados: [
      { nombre: "Tía Eva y esposo", enlace: "tia-eva" },
      { nombre: "Julian, esposa y 2 hijas", enlace: "julian" },
      { nombre: "Yessica", enlace: "yessica" },
      { nombre: "Tío Gerardo y esposa", enlace: "tio-gerardo" },
      { nombre: "Joe y Anthony", enlace: "joe-y-anthony" },
      { nombre: "Sebastian", enlace: "sebastian" },
      { nombre: "Tío Jorge y esposa", enlace: "tio-jorge" },
      { nombre: "Yohana y esposo", enlace: "yohana" },
      { nombre: "Leo", enlace: "leo" },
      { nombre: "Tía Nora, Alef y Juliana", enlace: "tia-nora" },
      { nombre: "Luis y esposa", enlace: "luis" },
      { nombre: "Maicol", enlace: "maicol" },
      { nombre: "Exon", enlace: "exon" },
      { nombre: "Tía Yineth y esposo", enlace: "tia-yineth" },
      { nombre: "Tania y Carlos", enlace: "tania-y-carlos" },
    ],
  },
  {
    grupo: "Lista 2",
    invitados: [
      { nombre: "Tía Marlen y esposo", enlace: "tia-marlen" },
      { nombre: "Leo y novia", enlace: "leo-y-novia" },
      { nombre: "Geiner, esposa y 2 hijos", enlace: "geiner" },
      { nombre: "Tía Blanca", enlace: "tia-blanca" },
      { nombre: "Juan Carlos Garcia y esposa", enlace: "juan-carlos-garcia" },
      { nombre: "Edward y esposa", enlace: "edward" },
      { nombre: "Jani y esposo", enlace: "jani" },
      { nombre: "Dana y esposo", enlace: "dana" },
      { nombre: "Eduardo Garcia y esposa", enlace: "eduardo-garcia" },
      { nombre: "Natilia y novio", enlace: "natilia" },
      { nombre: "Tía Myriam", enlace: "tia-myriam" },
      { nombre: "Jeisson y novia", enlace: "jeisson" },
      { nombre: "Jonathan, esposa y 3 hijos", enlace: "jonathan" },
      { nombre: "Tía Yolanda y esposo", enlace: "tia-yolanda" },
      { nombre: "Sebastian y novia", enlace: "sebastian-y-novia" },
      { nombre: "Leidy y novia", enlace: "leidy" },
    ],
  },
  {
    grupo: "Lista 3",
    invitados: [
      { nombre: "Juanfe y Jules", enlace: "juanfe-y-jules" },
      { nombre: "Simio y Geral", enlace: "simio-y-geral" },
      { nombre: "Carl y Angela", enlace: "carl-y-angela" },
      { nombre: "Cantor", enlace: "cantor" },
      { nombre: "Juan DC", enlace: "juan-dc" },
      { nombre: "Mus", enlace: "mus" },
      { nombre: "Sampol y Keily", enlace: "sampol-y-keily" },
      { nombre: "Estefany", enlace: "estefany" },
      { nombre: "Jhenner y Nicol", enlace: "jhenner-y-nicol" },
      { nombre: "Malonso", enlace: "malonso" },
      { nombre: "Gotza", enlace: "gotza" },
      { nombre: "Yeik", enlace: "yeik" },
      { nombre: "Don Camilo y esposa", enlace: "don-camilo" },
      { nombre: "Edu Piña", enlace: "edu-pina" },
      { nombre: "Gollum, esposa e hijo", enlace: "gollum" },
    ],
  },
  {
    grupo: "Lista 4",
    invitados: [
      { nombre: "Mamá", enlace: "mama" },
      { nombre: "Papá", enlace: "papa" },
      { nombre: "Caro y Michael", enlace: "caro-y-michael" },
      { nombre: "Marisol y Helen", enlace: "marisol-y-helen" },
      { nombre: "Tatiana, esposo y bebé", enlace: "tatiana" },
      { nombre: "Adriana, esposo e hijos", enlace: "adriana" },
      { nombre: "Miguel Ángel y acompañante", enlace: "miguel-angel" },
      { nombre: "Jocelin, tía Luisa e hijo", enlace: "jocelin" },
      { nombre: "Diego Gaitan", enlace: "diego-gaitan" },
      { nombre: "Valentina y esposo", enlace: "valentina" },
      { nombre: "Nicolas e Ingrid Gaitan", enlace: "nicolas-e-ingrid" },
      { nombre: "Fernanda, esposo e hija", enlace: "fernanda" },
      { nombre: "Naren Julia, esposa y 2 hijos", enlace: "naren-julia" },
      { nombre: "Geral, esposo y 3 hijos", enlace: "geral" },
      { nombre: "Tío Balbino, acompañante y Sara", enlace: "tio-balbino" },
      { nombre: "Marta Gaitan", enlace: "marta-gaitan" },
      { nombre: "Cristian Gaitan, acompañante e hijos", enlace: "cristian-gaitan" },
      { nombre: "Carol Gaitan", enlace: "carol-gaitan" },
      { nombre: "Oscar Gaitan, esposa e hijo", enlace: "oscar-gaitan" },
      { nombre: "Carmen Gaitan", enlace: "carmen-gaitan" },
      { nombre: "Moisa, esposa e hijo", enlace: "moisa" },
      { nombre: "Yadira Gaitan e hijas", enlace: "yadira-gaitan" },
      { nombre: "Amanda Gaitan", enlace: "amanda-gaitan" },
      { nombre: "Jorge Gaitan e hija", enlace: "jorge-gaitan" },
      { nombre: "Valentina Betancourt", enlace: "valentina-betancourt" },
      { nombre: "Viviana Romero y esposo", enlace: "viviana-romero" },
      { nombre: "Michael Paredes", enlace: "michael-paredes" },
      { nombre: "Jhon Castaño", enlace: "jhon-castano" },
    ],
  },
];
